### PR TITLE
Allow adding custom element class names

### PR DESCRIPTION
**Pull request by samuel-olivier**
The purpose of this is to allow tweaking the default style, for example adding a text ellipsis on the tooltip.

### CODE REVIEW

**Comment by mmacfadden** [comment]
Thank you. I will review.

**Review by alalonde — CHANGES_REQUESTED** [review]
Thanks! I think this is a good addition, but the `classnames` library dependency seems unnecessary. Could you provide an implementation that doesn't require it?

**Comment by samuel-olivier** [comment]
Hi @alalonde, does this PR seems ok to you ?

**Review by alalonde — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
